apiVersion: 1

# tells grafana where to find the prom connection
datasources:
  - name: 'prometheus'
    type: 'prometheus'
    access: 'proxy'
    url: 'http://prometheus:9090'
  - name: 'jaeger'
    type: 'jaeger'
    access: 'proxy'
    url: 'http://jaeger-all-in-one:16686'